server:
  port: 9006

spring:
  application:
    name: ACCOUNT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-service-registry-vk.herokuapp.com/eureka/
    #      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost